package com.zhaiyz.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.zhaiyz.model.Book;

import com.zhaiyz.service.BookLocalServiceUtil;

/**
 * The extended model base implementation for the Book service. Represents a row in the &quot;LP_Book&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BookImpl}.
 * </p>
 *
 * @author zhaiyz
 * @see BookImpl
 * @see com.zhaiyz.model.Book
 * @generated
 */
public abstract class BookBaseImpl extends BookModelImpl implements Book {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a book model instance should use the {@link Book} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            BookLocalServiceUtil.addBook(this);
        } else {
            BookLocalServiceUtil.updateBook(this);
        }
    }
}
